### ISSUE TITLE
Javascript does not support the exported functions as they include : 

### ISSUE THREAD

**Issue by Cmoen11** [mkafrin/PolyZone#38]
As the title describes. It's impossible to use the exports in javascript, as their function name includes the `:` char... 

such as:
`CircleZone:Create`

It would be awesome if this could be renamed to CircleZone_Create
or add export to accommodate this

**Comment by mkafrin** [comment]
These are not exports, they are methods on the object CircleZone, BoxZone, etc. That syntax `object:method()` (that exports also use) is a part of Lua. This resource is only built for Lua, because exposing these objects through exports would be difficult, since their methods don't really port over.

However, you could make a wrapper resource that create the zones in Lua (via export) and triggers an event when the player enters/exits them (using `onPlayerInOut`). Then you handle that event in Javascript. That's what servers I work with do and it's worked well for us.

**Comment by Cmoen11** [comment]
Thanks for an informative response :) 
I think I've found a repo that actually does what you've suggested.

For those who are also struggling with this, here's a wrapper 👍 
https://github.com/brentN5/bt-polyzone
