### ISSUE TITLE
Permissions for create functions

### ISSUE THREAD

**Issue by ResqDiver1317** [mkafrin/PolyZone#47]
Is there any type of ACE perms or anything on the creation script or would anyone be able to access it? I'd like to restrict it to just our staff team.

**Comment by mkafrin** [comment]
Currently there isn't any perms because it just shouldn't be enabled while in production (creation script only makes sense when developing/on test server). I thought I had a check for a convar, but I guess I didn't. Probably easiest way is to just wrap the `commands.lua` file contents in a if statement, like so:

```lua
if GetConvar("sv_environment", "prod") == "debug" then
  -- contents of commands.lua file
end
```
