### ISSUE TITLE
Circle entityzone?

### ISSUE THREAD

**Issue by regalonefour** [mkafrin/PolyZone#48]
Not an issue but wondering if it is posssible to give the option to create a circle entity zone rather than just a box zone?

**Comment by mkafrin** [comment]
Hmm, I've avoided doing it before because I figured most people would just use a distance check. I made EntityZones as box zones because there's a lot of additional logic involved for box zones (compared to just a dist check for circle zones).

But if it's something you think you'd find a use for, I can think about adding it to the next update. No guarantees, but I'll add the feature request label to this and leave it open until I make a decision.

**Comment by ItsANoBrainer** [comment]
+1
