### ISSUE TITLE
Resetting keybinds?

### ISSUE THREAD

**Issue by Zoaron** [mkafrin/PolyZone#49]
i cant use my scroll down to adjust the polyzone anymore, it was working fine previously. how do i fix this? can i reset the keybind?

**Comment by Zoaron** [comment]
hi im on fivem b2545 
im trying to create a polyzone box below is a video of how im trying to use my scroll wheel, works only scrolling up 

https://streamable.com/p6sil1

**Comment by mkafrin** [comment]
Hmm, not really sure tbh. I just tested on b2545 myself on a server with no other resources and it works perfectly fine. It's possible another resource is stealing the input or otherwise messing it up. Maybe try running your server only with PolyZone running to check if that's the case.

Otherwise, while there isn't a config for it currently, you can change the keybinds in the code if you want. They are here:
https://github.com/mkafrin/PolyZone/blob/9ae6d417803cd1eda5f91500ba42aabf3340ee79/creation/client/BoxZone.lua#L10-L11
and here:
https://github.com/mkafrin/PolyZone/blob/9ae6d417803cd1eda5f91500ba42aabf3340ee79/creation/client/BoxZone.lua#L21-L22

You'd change `81` and/or `99` to w/e keycode you wanted (codes can be found here https://docs.fivem.net/docs/game-references/controls/). IIRC, the first is scroll wheel down and the second is up, but I may have that backwards The same lines of code exist in [`creation/client/CircleZone.lua`](https://github.com/mkafrin/PolyZone/blob/master/creation/client/CircleZone.lua)

**Comment by Zoaron** [comment]
it might have something to do with my client side? my teammate say his polyzone is working fine even tho we are using the same server files.. any idea where polyzone stores the cache? i have tried uninstalling fivem and redownloading my server files as well

**Comment by Zoaron** [comment]
okay i tried to bind the key bind to another number which is 14 and it works.
i finally found out the issue i reset my gtav bindings to default which set the INPUT_VEH_NEXT_RADIO key bind to something else. so if corresponds to that binding. 

For anyone encountering this issue. please check this key bind under your keybinding > vech general > next radio station

Thanks for the help !

**Comment by mkafrin** [comment]
No problem. And just for future information, 81 and 99 are scroll wheel up *and* down, I just couldn't remember which is which.
