### ISSUE TITLE
[Bug] Z Scale in BoxZones

### ISSUE THREAD

**Issue by zf-development** [mkafrin/PolyZone#56]
Hi, I've observed that the scale in the boxzone doesn't work.

Currently, I was this BoxZone's code.
```
BoxZone:Create(v.outdoor, 2.0, 2.0, {
  name = tostring(_ .. 'outdoor'),
  scale = {0.75, 0.75, 0.35, 0.35, 0.25, 0.75},
  debugPoly = true
})
```

The BoxZone that's created is way bigger in height that was is supposed to be.
![image](https://user-images.githubusercontent.com/48424078/163684770-6fcf4741-ab36-4aad-a3aa-742edd48234f.png)

Thanks for information/fix.

**Comment by mkafrin** [comment]
So a couple of things are going on here. First of all, you don't have a minZ and maxZ in the options of your `BoxZone:Create` call, so what you're seeing here is actually not a bug, but intended behavior. When the minZ and maxZ are nil on a BoxZone, the BoxZone stretches to infinity on the Z axis. To be clear, the `2.0, 2.0` you are passing to `BoxZone:Create` are the length and width of the BoxZone. The `scale` option is _not_ the size of the zone, it multiplies the size of the zone.

In general, if possible it's better to set your length and width (2.0 and 2.0 in your case) and your minZ and maxZ to the final values you want, rather than using scale/offset to tweak them. The PolyZone creation commands (https://github.com/mkafrin/PolyZone/wiki/Using-the-creation-script) are useful for this, as they allow you to tweak the position, length, width, and height to exactly what you want, without needing to use the scale or offset options.

At the same time, funnily enough, scale and offset on the Z axis was indeed broken for BoxZones, so even if you had added those options, it wouldn't have worked. I have fixed this in commit bf913070907d79cbe234ac46f859b498c86a8dd7.

To get this fix, you can download the latest release (https://github.com/mkafrin/PolyZone/releases/tag/v2.6.1) and also add `minZ` and `maxZ` to the options you are passing to `BoxZone:Create`. For reference, these options are mentioned [here](https://github.com/mkafrin/PolyZone/wiki/PolyZone#options-for-a-polyzone-instance).

I'll leave this issue open for the next day if you have any additional questions.
