### ISSUE TITLE
[Features] Add exports

### ISSUE THREAD

**Issue by CitarOff** [mkafrin/PolyZone#57]
Hello,

I develop in JS, and I can't use the LUA metatables, would it be possible to export the functions ?

Thank's ! 
I like your script

**Comment by mkafrin** [comment]
This was developed in lua due to the vector primitives being very fast. Exports would massively slow things down if used directly for the zone functions and I don't want to officially support it at this time.

My suggestion in the past has been to create a zone manager lua resource that can create zones with exports and then triggers events on player enter and exit of any of those created zones. An official version of this may exist at some point, but for now I suggest you check out something like `bt-polyzone` or make your own manager.
