### ISSUE TITLE
EntityZone doesn't handle rotation

### ISSUE THREAD

**Issue by regalonefour** [mkafrin/PolyZone#60]
Hey, noticed this while working with entity zones, they don't take into account entity rotation on the y axis it seems?

https://i.imgur.com/QQ0kG00.jpeg
https://i.imgur.com/sjxW3ZO.jpeg

**Comment by mkafrin** [comment]
This is intentional and a side-effect of needing to stay performant. Checking if a point is in a box that can only be rotated on one axis is very fast. Allowing that box to rotate on all axis would make it many multiples slower.

EntityZones were originally made to work with things that only really rotated on one axis, so this limitation was fine at the time, but if your use case is limited by this, unfortunately EntityZones won't work for it as of now.

The functionality may be added in the future, but only if I can find a way to do it performantly.
