### ISSUE TITLE
Couldn't load resource PolyZone: Couldn't parse URI.

### ISSUE THREAD

**Issue by R4ndGuy** [mkafrin/PolyZone#64]
Hello,

when I run PolyZone while connected I get kicked from the server with this error "Couldn't load resource PolyZone: Couldn't parse URI.", and I couldn't connect.

I first thought of an error in the file tree but yet all the paths seem correct.

Do you have an idea ?

sorry for the rough translation

screenshot of my files path
![image](https://user-images.githubusercontent.com/108875344/177770552-b102d7f6-d0d0-4853-9215-8a5a8e278370.png)
![image](https://user-images.githubusercontent.com/108875344/177770658-37bb8a44-8469-4bb1-981d-04b72f86ff81.png)

![image](https://user-images.githubusercontent.com/108875344/177771439-9ddfca8e-2da2-4e29-9c5b-ab2d7625ca07.png)

**Comment by mkafrin** [comment]
I certainly have not seen this before. Did you change anything about the resource after downloading it? What fxserver version are you running and what operating system are you using? Also, does your server console have any errors relating to PolyZone when you start the server?

**Comment by R4ndGuy** [comment]
Hello,

The server is running on version v1.0.0.5562 and not any server error, only a client error and the inability to reconnect to the server.

I didn't touch the script, just copy paste and try to start it.

**Comment by mkafrin** [comment]
And what's your operating system? Also can you show me the whole path of the resource, up to the resources folder?

**Comment by mkafrin** [comment]
Hmm yeah this may be a linux vs windows thing. I've never run fxserver or FiveM on linux and am not sure what possible changes there may be.

Can you show me the whole path of the resource, up to the resources folder? Also, can you try removing the lines for the creation scripts in your fxmanifest.lua (line 13 and 17 in the screenshot above).

**Comment by jnccloud** [comment]
I've been using PolyZone on Linux for a year now. If you are receiving an error like that, it's most likely due to the case sensitivity in Linux. Ensure that if you manually recreated ANY files in the resource that any references to those are also matching case. Everywhere from the server.cfx, fxmanifest and anything that requires PolyZone (dependency 'PolyZone')

It could also be an issue with your distro (I use CentOS) that does not like the globbing in fxmanifest (server/*.lua, client/*.lua); try manually adding each file into the fxmanifest and remove the wildcard glob reference.

**Comment by mkafrin** [comment]
Oops, I totally lost track of this, apologies. Thank you for lending your experience of PolyZone on Linux @jnccloud, I really appreciate that. Can you take a look at his comment @R4ndGuy and see if either of those suggestions helps?
