### ISSUE TITLE
Question: How to get the current zone a player is in

### ISSUE THREAD

**Issue by PandaPlayZLP** [mkafrin/PolyZone#66]
Hey, maybe I am just blind (or stupid, who knows), but is there a way to check if the player currently is inside any Polyzone and get the data from it? Just found the checking for it on a specific Polyzone on the docs but no real check for all currently existing ones.

**Comment by mkafrin** [comment]
Calling `onPlayerInOut` on a zone will trigger a callback you pass to it whenever the player enters the zone (mentioned [here](https://github.com/mkafrin/PolyZone/wiki/Testing-a-point)). To do this for a collection of zones, you can can wrap all your zones in a ComboZone, and call `onPlayerInOut` on that, instead of calling it on each individual zone (discussed [here](https://github.com/mkafrin/PolyZone/wiki/ComboZone)).

So a common pattern people follow is to create a PolyZone manager resource that keeps all the zones in one ComboZone and uses `onPlayerInOut` on that. There's a couple open source ones, or you can just make it yourself if you'd like.

**Comment by PandaPlayZLP** [comment]
Thanks for your quick answer. Do you maybe got a link to one of those managers?

**Comment by mkafrin** [comment]
Only one I can remember is https://github.com/brentN5/bt-polyzone, but it doesn't use ComboZones, which is a lot less efficient, so I'd suggest modifying it to do so if you do use it.

**Comment by PandaPlayZLP** [comment]
Gonna do that. Thank you for your quick support!
