### ISSUE TITLE
Debug wall drawing optimized

### ISSUE THREAD

**Issue by vietgamingnetwork** [mkafrin/PolyZone#68]
Dear PolyZone dev team's,
I have some ideas bellow:
- Toggle on/ off wall drawing helper function after created.
- Toggle on/ off wall drawing in range configs.
I think it's more optimized for PolyZone, because i see the benchmark score when on and off have another value, no wall will have good score. In case i can make destroy and recreate but two functions, configs above will be good, i think.
Best regards.

**Comment by mkafrin** [comment]
Thank you for the suggestions, but the debug drawing should only be used for debugging and therefore not a lot of time was spent on optimizing them. Adding additional code and options for something that doesn't have any effect outside of local testing is not something I want to do.

It would take drawing a lot of zones to actually heavily effect FPS (where it would matter for testing purposes), but if you want to optimize it yourself, the `draw`  method on zones is freely available to be run manually rather than using the built-in debug options.
