### ISSUE TITLE
Z

### ISSUE THREAD

**Issue by ahmoge** [mkafrin/PolyZone#70]
when I press "z" nothing happens, how to fix this?

**Comment by erikmeyer08** [comment]
Stop the qb-target resource if your using it.

**Comment by mkafrin** [comment]
Sorry, I must have missed this somehow when it was first posted. Agree with erik here. This issue is almost always caused by some other resource enabling the control while PolyZone relys on the control being disabled (see https://github.com/mkafrin/PolyZone/blob/master/creation/client/BoxZone.lua#L87). To verify if this is happening (which would be useful to determine next steps), I'd try disabling all other resources then retesting the creation.

Also, it'd be nice to have some additional info here, specifically, what type of zone you are trying to create, and what commands you used to start the creation.
