### ISSUE TITLE
Add support for Javascript or add exports

### ISSUE THREAD

**Issue by GttMone** [mkafrin/PolyZone#90]
It would be really nice if you add support for JavaScript or add exports that can be used instead of functions and importing the client script.

**Comment by mkafrin** [comment]
PZ is done in lua because of access to the much faster native vectors. Adding exports to directly call things like isPointInside would introduce massive overhead. In the past the way to get JS support has been to have a PZ manager script in lua that has a combozone that keeps track of all zones, exports to add zones to that combozone, and then it fires off events for when the player goes in and out of zones. Many third party scripts for this exist, though I may make an official one at some point. Direct JS support or exports isn't in the cards right now tho.

**Comment by GttMone** [comment]
Thanks for the explanation! For now I'll use ps-zones until you release an official resource. Have a nice day

**Comment by mkafrin** [comment]
ps-zones is a good one! Have a nice day as well!
