### ISSUE TITLE
pzcreate box

### ISSUE THREAD

**Issue by idrp** [mkafrin/PolyZone#94]
Not sure why, but I can not see the box when using pzcreate box after filling in the details of name, length and width.  Is there a setting I need to use to be able to see the box when creating?

**Comment by Chisomraph** [comment]
mee too 
fiqured it out yet??

**Comment by DrAceMisanthrope** [comment]
[Commit 9ff0d05](https://github.com/mkafrin/PolyZone/commit/9ff0d0557989f090bac67c2e91abe65ddb4e7956) caused this issue.

When using `/pzcreate box` the debugPoly isn't drawing because of this line that was added in.
https://github.com/mkafrin/PolyZone/blob/9ff0d0557989f090bac67c2e91abe65ddb4e7956/client.lua#L129
But changing it to include `drawZone` which is true while creating a zone, makes it work again.
```lua
if not self.debugPoly and not self.debugGrid and not drawZone then return end
```
I am sure there is a better fix which allows debugPoly to be visible when creating a zone, independent of other's debugPoly and debugGrid settings. However this change will help people currently having the issue of being unable to see the box zones they are creating.

**Comment by mkafrin** [comment]
@DrAceMisanthrope Ah, definitely an unintended consequence, nice catch! I'll think on it and either put this or another fix in tomorrow. Thank you.
